#!/bin/bash

# jeudi 22 08 2016, 08:59:10 (UTC+0200)

# If you like to live dangerously:
# curl https://raw.githubusercontent.com/remipassmoilesel/linux-utils/master/config-helpers/cli-config | bash

# Small script to set up a shell withmust-have tools

echo
echo "Running script for user $USER"
echo

# Install must-have tools, two commands to prevent fail
PACKAGES=(
    "byobu vim curl wget ranger"
    "git tig git-extras"
    "zsh jq cmatrix"
    "p7zip-full p7zip-rar zip fuse-zip tar xz-utils"
    "tcpdump htop nmap iputils-tracepath traceroute"
    "sshpass sshfs ncdu gnupg2 mycli pgcli"
    "aptitude"
);

sudo apt-get update
for pkg in "${PACKAGES[@]}"; do
  echo ""
  echo "========== Installing: $pkg =========="
  echo ""
  sudo apt install -y $pkg || :
done

# Get utilities and scripts
git clone https://github.com/remipassmoilesel/linux-utils ~/linux-utils/

# change shell before installing oh my zsh
sudo chsh $USER -s /bin/zsh

# install oh my zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/remipassmoilesel/oh-my-zsh ~/.oh-my-zsh

# install autocomplete plugin
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions 

# copy configuration
cp ~/linux-utils/configuration/zshrc ~/.zshrc

zsh

