#!/bin/bash

# set -x

export PATH="$PATH:$HOME/linux-utils/"
export PATH="$PATH:$HOME/linux-utils/notes/"
export PATH="$PATH:$HOME/linux-utils/memo/"
export PATH="$PATH:$HOME/linux-utils/linux-config-helpers/"
export PATH="$PATH:$HOME/bin/"
export PATH="$PATH:$HOME/go/bin/"
export PATH="$PATH:$HOME/npm-root/bin"

# default editor
export EDITOR=vim

export GOPATH=$HOME/go

# history format and behavior
export HISTTIMEFORMAT='%d %H:%M '
PROMPT_COMMAND='history -a'

# inclure le path courant dans la commande sudo
# alias sudo='sudo env PATH=$PATH '

# better git log with 'git lg'
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

if [ -f ~/.custom-rc ]; then
    echo "Sourcing $HOME/.custom-rc"
    source $HOME/.custom-rc
fi

if [ -f /usr/share/bm/bm.bash ]; then
    source /usr/share/bm/bm.bash
    alias cm="cdbm $@"
fi

alias kubesys="kubectl -n kube-system $@"
alias ks="kubectl -n kube-system $@"
alias k="kubectl $@"
alias k-watch-all-pods="watch -n 0,5 kubectl get pods --all-namespaces"
alias k-watch-pods="watch -n 0,5 kubectl get pods"
alias ks-watch-pods="watch -n 0,5 kubectl get pods -n kube-system"

if [ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
	source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

export ANSIBLE_COW_SELECTION=tux

# woooo !
cmatrix -b  -C blue

