#!/bin/bash

# set -x

##
## PATH OPTIONS
##

export PATH="$PATH:$HOME/linux-utils/"
export PATH="$PATH:$HOME/linux-utils/notes/"
export PATH="$PATH:$HOME/linux-utils/memo/"
export PATH="$PATH:$HOME/linux-utils/config-helpers/"
export PATH="$PATH:$HOME/bin/"
export PATH="$PATH:$HOME/go/bin/"
export PATH="$PATH:$HOME/npm-root/bin"

export GOPATH=$HOME/go

##
## EDITOR OPTIONS
##

export EDITOR=vim

##
## HISTORY OPTIONS
##

export HISTTIMEFORMAT='%d %H:%M '
export PROMPT_COMMAND='history -a'

# see https://github.com/dvorka/hstr/blob/master/README.md
if type "hh" > /dev/null; then
	export HISTFILE=~/.zsh_history  # ensure history file visibility
	export HH_CONFIG=hicolor        # get more colors
	bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)
fi

# see https://github.com/zsh-users/zsh-autosuggestions
if [ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
	source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

setopt hist_ignore_all_dups  # ignore duplicate entries
setopt hist_ignore_space     # ignore commands prefixed with space

##
## GIT OPTIONS AND ALIASES
##

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"


##
## ALIASES
##

alias k="kubectl "
alias ks="kubectl -n kube-system"
function ka() { kubectl "$@" --all-namespaces ;}

alias k-watch-pods="watch -n 0,5 kubectl get pods"
alias ks-watch-pods="watch -n 0,5 kubectl get pods -n kube-system"
alias ka-watch-pods="watch -n 0,5 kubectl get pods --all-namespaces"

if [ -f /usr/share/bm/bm.bash ]; then
    source /usr/share/bm/bm.bash
    alias cm="cdbm"
fi

##
## SDKMAN
##

if [ -d "/home/$USER/.sdkman/bin/sdkman-init.sh" ]; then
    source "/home/$USER/.sdkman/bin/sdkman-init.sh"
fi

##
## SUPP. OPTIONS DEPENDS ON ENV.
##

if [ -f ~/.custom-rc ]; then
    echo "Sourcing $HOME/.custom-rc"
    source $HOME/.custom-rc
fi


#
# WOOOOOO !
#

export ANSIBLE_COW_SELECTION=tux
cmatrix -b  -C blue

