#!/bin/bash

# lundi 2 avril 2018, 19:40:36 (UTC+0200)

if [[ -z "$1" ]] ; then
	echo "You must provide a destination."
	exit 1
fi

if [[ -z "$2" ]] ; then
	echo "You must provide a repo name."
	exit 1
fi

GIT_ROOT="/git"
NEW_REPO="$GIT_ROOT/$2"

ssh $1 "

echo As user \$USER, 

echo ... creating repertory $NEW_REPO
if [ ! -d \"$NEW_REPO\" ]; then
	mkdir /git/$2
else
	echo Already exist !
fi

echo ... and initalizing new repository !
if [ ! -d \"$NEW_REPO/branches\" ]; then
	cd /git/$2 && git init --bare
else
        echo Already initialized !
fi


"

echo 
echo "Use commands:"
echo "	git remote rm $1; git remote add $1 ssh://$1:$NEW_REPO; git push --set-upstream $1 master"

