#!/bin/bash

# mercredi 11 octobre 2017, 22:23:39 (UTC+0200)

echo Test failled : $(cat $1 | grep -i failing | wc -l)
echo Test passed  : $(cat $1 | grep -i passing | wc -l)
echo Test skipped : $(cat $1 | grep -i skipped | wc -l)
