#!/bin/bash
# Script de lancement d'application au démarrage de la session

# Documents
# xdg-open "/home/remipassmoilesel/Documents/coursCyrilVincent/Les Design Patterns en Java.pdf" &

# Operations diverses
# ...

# Journal d'éxécution, chemins absolus uniquement
START_LOG="/home/remipassmoilesel/start.log"

# Date du jour
echo
echo "### Starting: " `date` >> $START_LOG

# Sauvegarde
echo 
echo "##! Backup: "
/home/remipassmoilesel/linux-utils/backup -w &>> $START_LOG &
echo	

# mise à jour des gestionnaires
# apt-get update &>> $UPDATE_LOG &
# apt-file update &>> $UPDATE_LOG &

