#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os

scriptDir = os.path.dirname(os.path.realpath(__file__))
sourceDir = os.path.join(scriptDir, 'src')
sys.path.insert(0, sourceDir)

from ArgumentParser import ArgumentParser
from Logger import Logger
from Configuration import Configuration

if __name__ == "__main__":

    try:
        parser = ArgumentParser()
        parser.parseArguments()
    except Exception as e:
        Logger.error(str(e))

        if Configuration.DEBUG:
            raise e

        exit(1)
