#!/bin/bash

# samedi 28 octobre 2017, 14:37:38 (UTC+0200)


cd /tmp

wget https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip?_ga=2.87796568.1107687076.1509194273-658121432.1508602791 -o terraform.zip

unzip terraform.zip

sudo mv terraform /usr/bin/terraform
sudo chmod +x /usr/bin/terraform

