#!/bin/bash

# jeudi 22 08 2016, 08:59:10 (UTC+0200)

# If you like to live dangerously:
# curl https://raw.githubusercontent.com/remipassmoilesel/linux-utils/master/config-helpers/cli-config | bash

# Small script to set up a shell withmust-have tools


cat << Banner

██╗     ██╗███╗   ██╗██╗   ██╗██╗  ██╗    ██╗   ██╗████████╗██╗██╗     ███████╗
██║     ██║████╗  ██║██║   ██║╚██╗██╔╝    ██║   ██║╚══██╔══╝██║██║     ██╔════╝
██║     ██║██╔██╗ ██║██║   ██║ ╚███╔╝     ██║   ██║   ██║   ██║██║     ███████╗
██║     ██║██║╚██╗██║██║   ██║ ██╔██╗     ██║   ██║   ██║   ██║██║     ╚════██║
███████╗██║██║ ╚████║╚██████╔╝██╔╝ ██╗    ╚██████╔╝   ██║   ██║███████╗███████║
╚══════╝╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝  ╚═╝     ╚═════╝    ╚═╝   ╚═╝╚══════╝╚══════╝

Banner

echo
echo "Running script for user $USER"
echo

# Install must-have tools, two commands to prevent fail
PACKAGES=(
    "byobu vim curl wget ranger ncdu gnupg2 aptitude zsh jq cmatrix tree"
    "git tig git-extras python-pip sshpass sshfs mycli pgcli"
    "p7zip-full p7zip-rar zip fuse-zip tar xz-utils"
    "tcpdump htop nmap iputils-tracepath traceroute"
);

sudo apt-get update

for pkg in "${PACKAGES[@]}"; do
  echo ""
  echo "========== Installing: $pkg =========="
  echo ""
  sudo apt install -y $pkg || :
done

# Rust !
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup install nightly
rustup default nightly

cargo install notes

# Get utilities and scripts
git clone https://github.com/remipassmoilesel/notes-repository ~/.notes
git clone https://github.com/remipassmoilesel/linux-utils ~/linux-utils/
git submodule init
git submodule update

# Change shell before installing oh my zsh
sudo chsh ${USER} -s /bin/zsh

# install oh my zsh
REPO=remipassmoilesel/ohmyzsh BRANCH=develop sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

# install autocomplete plugin
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

# copy zsh configuration
cp ~/linux-utils/configuration/dot-files/dot-zshrc ~/.zshrc

zsh

