#!/bin/bash

# set -x

##
## PATH OPTIONS
##

export PATH="$PATH:$HOME/linux-utils"
export PATH="$PATH:$HOME/linux-utils/notes"
export PATH="$PATH:$HOME/linux-utils/memo"
export PATH="$PATH:$HOME/linux-utils/configuration/helpers"
export PATH="$PATH:$HOME/linux-utils/bin"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.go/bin"
export PATH="$PATH:$HOME/npm-root/bin"
export PATH="$PATH:$HOME/.cargo/bin"

export GOPATH="$HOME/.go"

export MEMO_STORAGE_PATH="$HOME/linux-utils/memo-rs/memo-storage.txt"

##
## EDITOR OPTIONS
##

export EDITOR=vim

##
## HISTORY OPTIONS
##

export HISTTIMEFORMAT='%d %H:%M '
export PROMPT_COMMAND='history -a'

# see https://github.com/dvorka/hstr/blob/master/README.md
if type "hh" > /dev/null; then
	export HISTFILE=~/.zsh_history  # ensure history file visibility
	export HH_CONFIG=hicolor        # get more colors
	bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)
fi

# see https://github.com/zsh-users/zsh-autosuggestions
if [ -f ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
	source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

setopt hist_ignore_all_dups  # ignore duplicate entries
setopt hist_ignore_space     # ignore commands prefixed with space

##
## GIT OPTIONS AND ALIASES
##

git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

##
## ALIASES
##

#alias k="kubectl" # Provided by oh-my-zsh plugin
alias ks="kubectl -n kube-system"
function ka() { kubectl "$@" --all-namespaces ;}

alias kgn="kubectl get namespaces"
function ksn(){ kubectl config set-context $(kubectl config current-context) --namespace=$1 }

alias k-watch-pods="watch -n 0,5 kubectl get pods"
alias ks-watch-pods="watch -n 0,5 kubectl get pods -n kube-system"
alias ka-watch-pods="watch -n 0,5 kubectl get pods --all-namespaces"

alias kcgc="kubectl config get-contexts"

alias kp="kubectl proxy"
alias kpf="kubectl port-forward"

alias xo="xdg-open"

alias cl="clear"
alias re="reset"
alias rh="rehash"

alias tr="tree -L 2"

alias lst="lsd --tree"


##
## MAVEN
##

MAVEN_OPTS="-T 1C -Djava.net.preferIPv4Stack=true"

##
## SDKMAN
##

if [ -d "/home/$USER/.sdkman/bin/sdkman-init.sh" ]; then
    source "/home/$USER/.sdkman/bin/sdkman-init.sh"
fi

##
## SUPP. OPTIONS DEPENDING ON LOCAL CONFIG
##

if [ -f ~/.custom-rc ]; then
    echo "Sourcing $HOME/.custom-rc"
    source $HOME/.custom-rc
fi

#
# WOOOOOO !
#

# export ANSIBLE_COW_SELECTION=random
export ANSIBLE_NOCOWS=1

CMATRIX_COLOR=blue
if [ "$USER" = "root" ]; then
	CMATRIX_COLOR=red
fi

cmatrix -b  -C $CMATRIX_COLOR


