set nocompatible              " be iMproved, required
set number
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" Utilisation de la souris
set mouse=a

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Formatage automatique du code. Usage ':autoformat'
Plugin 'Chiel92/vim-autoformat'

" Navigation dans l'arborescence de fichiers
Plugin 'scrooloose/nerdtree'

" Syntaxe javascript
"Plugin 'pangloss/vim-javascript'

Plugin 'scrooloose/syntastic'

" Vérifier la syntaxe lors de l'écriture et pas seulement de l'enregistrement
let g:syntastic_check_on_open=1

" syntastic requiert d'installer globalement jshint: 
" $ npm install -g jshint

" Autocompletion
Plugin 'Valloric/YouCompleteMe'

" These are the tweaks I apply to YCM's config, you don't need them but they might help.
" YCM gives you popups and splits by default that some people might not like, so these should tidy it up a bit for you.
let g:ycm_add_preview_to_completeopt=0
let g:ycm_confirm_extra_conf=0
set completeopt-=preview

" Exemple de syntaxe avec un plugin en local
"Plugin 'file:///home/gmarik/path/to/plugin'

" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
